### ISSUE TITLE
branch option

### ISSUE THREAD

**Issue by graemeblair** [eddelbuettel/drat#61] opened 2017-04-30 05:37 UTC
Thanks for this terrifically useful package.

The branch that drat commits, gh-pages, is hardcoded. This is sensible in general, but for user or organization Github pages (i.e. user.github.io) Github requires those files to be stored in the master branch of a repo named user.github.io. Because of the hardcoding, it isn't possible to use drat to create a drat repo in such a Github repo. 

What do you think of adding a field in insertPackage() for branch name, i.e. insertPackage(branch = "master")? Happy to add a PR.

**Comment by eddelbuettel** [comment] 2017-04-30 12:45
> a repo named user.github.io.

I think that had come up before and there was a reason not to do it.  Maybe it was mostly because 'user.github.io' webpages don't correspond to the 'github.com/user/drat' scheme.   

In any event one other (newer) change is worth considering too:  master branch and docs/ directory.  That is now permitted as an alternative.

The one thing I am a little wary about is the number of different code paths over the different helper functions.  We'd need at least `initRepo()` and `insertPackage()` changed.

**Comment by eddelbuettel** [comment] 2017-12-16 14:02
This too is now talken care of thank to @nfultz

**Comment by dracodoc** [comment] 2018-03-12 23:11
`gh-pages` is still hard-coded in `initRepo`. Is it supposed to come from option `dratBranch` now? I didn't this option is set by default.

I think an option is fine for this, but `initRepo` and `insertPackage` should also provide a parameter for one time settings.

**Comment by dracodoc** [comment] 2018-03-12 23:30
Added via #73

**Comment by eddelbuettel** [comment] 2018-03-12 23:56
If you are suggesting a minimal (two file, maybe?) PR to add support for `getOption("dratBranch", "gh-pages") to `initRepo()` then I would be favour as it works well enough in the existing function `insertPackage()`.

**Comment by dracodoc** [comment] 2018-03-12 23:59
The extreme minimal changes can be made with only changing `initRepo` and its .Rd file. However I felt it's easier to make one time adjustment for branch name with a parameter instead of options. 

The default value still use options, so previous usage will not be interfered.

**Comment by eddelbuettel** [comment] 2021-04-05 21:09
This can be closed, the lack of following suggests the issue is addressed.  If more is needed please reopen and ideally demonstrate with small reproducible examples why.

Also, we have that change working in 0.1.8.1 (i.e GitHub version of `drat`) and it will be in the next CRAN release "real soon".

**Closed by eddelbuettel** 2021-04-05 21:09 UTC
