### ISSUE TITLE
add binary package infrastructure (avoid errors when 'type != "source")

### ISSUE THREAD

**Issue by kevinushey** [eddelbuettel/drat#46] opened 2016-02-26 22:34 UTC
I've created a simple `drat` repository [here](https://github.com/kevinushey/drat), with a call to `drat::initRepo()` and then `drat::insertPackage("sashimi_0.0.1.tar.gz")` for a locally built package `sashimi`. All is well with:

```
install.packages("sashimi", type = "source")
```

However (as is default on non-Linux systems), using `type = "both"`

```
install.packages("sashimi", type = "both")
```

gives a warning:

```
curl: (22) The requested URL returned error: 404 Not Found
Warning in read.dcf(file = tmpf) :
  cannot open compressed file '/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T//RtmpyPMPgH/file9d6b4875028d', probable reason 'No such file or directory'
Warning: unable to access index for repository http://kevinushey.github.io/drat/bin/macosx/mavericks/contrib/3.2:
  cannot open the connection
```

Not surprising since `http://kevinushey.github.io/drat/bin/macosx/mavericks/contrib/3.2` does not exist.

It would be useful if `drat` populated the common binary 'arms' of the repository with an empty `PACKAGES` file by default, to avoid this warning.

Packrat has some repository management tools that help do this: 

https://github.com/rstudio/packrat/blob/master/R/cranlike-repositories.R#L31-L44
https://github.com/rstudio/packrat/blob/master/R/cranlike-repositories.R#L58-L71

Would you be willing to accept a PR that created skeletons for these paths?

**Comment by eddelbuettel** [comment] 2016-02-26 22:56
That sounds like a lightweight way to make a warning go away, so yes.

In general, I think of drat as supporting a _source-based_ workflow.  We support binaries if folks want them, but it is usually an extra (or different) step.   What you suggest seems to plug a hole, so :+1:

Thanks also for discussing first, especially as I've howling at another PR submitter all week to pretty-please discuss first (which he seems to abhor ...)

**Comment by csgillespie** [comment] 2016-02-28 22:05
Sorry @eddelbuettel  I referenced the wrong issue in that commit and I'm having trouble removing the reference.

**Comment by eddelbuettel** [comment] 2016-08-01 01:33
> Would you be willing to accept a PR that created skeletons for these paths?

I would.  Do you still have spare cycles to write one?

**Comment by FelixErnst** [comment] 2020-06-20 19:27
I got a branch to fix this. See https://github.com/FelixErnst/drat/tree/initRepo

**Comment by eddelbuettel** [comment] 2021-04-05 21:11
This can be closed, the lack of following suggests the issue is addressed.  If more is needed please reopen and ideally demonstrate with small reproducible examples why.

(This got fixed by @FelixErnst last year with a few really decent PRs.)

**Closed by eddelbuettel** 2021-04-05 21:11 UTC
