### ISSUE TITLE
Incorrect directory for macOS binaries under R 4.0.0

### ISSUE THREAD

**Issue by petrbouchal** [eddelbuettel/drat#87] opened 2020-05-18 22:27 UTC
On R 4.0.0 / macOS Catalina (10.15.4), when calling `drat::insertPackage()` on .tgz file, drat places Mac binaries into `[drat-repo]/mac.binary/contrib/4.0`.

According to the [R documentation](https://cran.r-project.org/doc/manuals/r-patched/R-admin.html), part 6.6, the correct directory for R 4.0.0 would be `bin/macosx/contrib/4.0`. 

This also produces a note (confusing to me since this is a binary package):

> Note: Non-binary OS X package will be installed in mac.binary path.

Am I right thinking this is a bug (the location and perhaps also the note?) I could of course be missing something...

From my limited understanding of the drat innards this happens at https://github.com/eddelbuettel/drat/blob/afbfe9394bac483bb69e9da872886394a059a101/R/insertPackage.R#L244, where the code assumes that `.Platform$pkgType` takes the form of `"mac.binary.[OSxFlavour]"`, wherease on R 4.0.0 this is just `"mac.binary"`.

**Comment by eddelbuettel** [comment] 2020-05-18 22:39
Sure. If you look at, _e.g._, `git blame` you will see that the `pkgtype == "mac.binary"` code was constributed by @nfultz about 2 1/2 years ago.  I don't use a macOS, so no change vector from me.

Clean PRs always welcome.  There is no reason that could not work for current macOS (apart from the apparent constant that "they" seem to change everything every couple of quarters...).

**Comment by petrbouchal** [comment] 2020-05-18 22:53
Thanks. Will try my hand at a PR.

**Comment by nfultz** [comment] 2020-05-18 23:30
I don't remember specifically, but I think the note (and the comment above it) is because when the package didn't actually require any compilation (DeclareDesign in that case), it didn't get the correct build metadata set to identify which version of R was used, so it guessed based on whatever Travis CI was doing back then.

**Comment by eddelbuettel** [comment] 2020-05-18 23:52
Could be. Is there any way we could anticipate / accomodate / ... rather than just breaking?

**Comment by nfultz** [comment] 2020-05-19 01:40
You _might_ be able to add a test that builds a binary, adds it to drat, and then installs from the drat repo. But it would have had to be run on a mac (with dev toolchain) to actually catch the failure, a docker wouldn't be able to reproduce it for example.

**Comment by eddelbuettel** [comment] 2020-05-19 01:42
Maybe other trickery.  Throwing it at a rhub macOS build and looking at the log to infer a path...

**Comment by eddelbuettel** [comment] 2020-05-25 20:21
Any updates on a possible macOS binary PR?

**Comment by eddelbuettel** [comment] 2020-05-29 12:25
@petrbouchal @nfultz There is now a PR in #89. Maybe you can take a look and/or take it for a spin?

**Comment by eddelbuettel** [comment] 2020-05-30 11:17
And the PR went, became a new version and is now on CRAN.  Assuming it works well I will close this here; feel free to reopen if it isn't.

**Closed by eddelbuettel** 2020-05-30 11:17 UTC

**Comment by petrbouchal** [comment] 2020-06-04 17:01
Many thanks to both of you - and sorry for the radio silence. Based on a quick test this now workd as expected.
